### ISSUE TITLE
A version subcommand

### ISSUE THREAD

**Issue by ssorj** [skupperproject/skupper-cli#2]
Similar in behavior to kubectl version:

```
[jross@localhost ~]$ kc version
Client Version: version.Info{Major:"1", Minor:"10+", GitVersion:"v1.10.0+d4cacc0", GitCommit:"d4cacc0", GitTreeState:"clean", BuildDate:"2018-12-06T18:30:39Z", GoVersion:"go1.11.2", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.2", GitCommit:"f6278300bebbb750328ac16ee6dd3aa7d3549568", GitTreeState:"clean", BuildDate:"2019-08-05T09:15:22Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"linux/amd64"}
```

In our case, it would be client plus the various server side components.  I'm thinking we'd want the image IDs here as well.

**Comment by grs** [comment]
Latest release adds a version subcommand which will list the version of the client (also available on its own by --version option) and the image version info for the router and proxy-controller.

**Comment by grs** [comment]
Closing for now. Any change requests can be handled through new issues.
