### ISSUE TITLE
skupper-expose branch fails to pull controller/proxy images

### ISSUE THREAD

**Issue by ChugR** [skupperproject/skupper-cli#24]
> skupper init

fails with

> Failed to pull image "quay.io/skupper/controller": rpc error: code = Unknown desc = repository quay.io/skupper/controller not found

**Comment by grs** [comment]
Yes, those don't exist yet! To fix, either use https://github.com/grs/skupper-cli/tree/preview or set the images as env vars before running skupper-init: 

export SKUPPER_PROXY_IMAGE=quay.io/gordons/skupper-proxy
export SKUPPER_CONTROLLER_IMAGE=quay.io/gordons/skupper-controller
