### ISSUE TITLE
expose deployment generates mis-configured service when target-port != port

### ISSUE THREAD

**Issue by ajssmith** [skupperproject/skupper-cli#29]
command:

skupper expose deployment emailservice --address emailservice --port 5000 --protocol http2 --target-port 8080

generates:

apiVersion: v1
kind: Service
metadata:
  annotations:
    internal.skupper.io/controlled: "true"
  creationTimestamp: 2020-02-13T19:21:44Z
  name: emailservice
  namespace: skupper
  ownerReferences:
  - apiVersion: apps/v1
    kind: Deployment
    name: skupper-router
    uid: d971de68-4e94-11ea-adbb-0ab39d0f400c
  resourceVersion: "389802"
  selfLink: /api/v1/namespaces/skupper/services/emailservice
  uid: 1226501c-4e96-11ea-adbb-0ab39d0f400c
spec:
  clusterIP: 172.30.220.74
  ports:
  - name: emailservice
    port: 5000
    protocol: TCP
    targetPort: 5000
  selector:
    internal.skupper.io/service: emailservice
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}

**Comment by grs** [comment]
@ajssmith the formatting of the service yaml has been lost be interpreting it as markdown I think. There is indeed a bug where the targetPort is not always properly recorded. However it will not actually be used as the targetPort in the service (which is backed by the proxy), but as the port the egress bridge will target. I've pushed a fix to master.
