### ISSUE TITLE
Consider renaming init to install

### ISSUE THREAD

**Issue by ssorj** [skupperproject/skupper-cli#7]
It strikes me that our docs and help text frequently refer to the "Skupper installation", which makes me think that maybe "skupper install" would be more natural and better link up the user concepts.

**Comment by ted-ross** [comment]
My vote is to leave this as "init".  I think the current set of verbs and nouns is good enough.

**Comment by ssorj** [comment]
As a data point, Camel K uses install.

https://github.com/apache/camel-k#installation

**Comment by grs** [comment]
I also prefer init. @ssorj are you ok with closing this issue or should we debate some more?

**Comment by ssorj** [comment]
After your explanation, I'm good with init.

The explanation was that init not only installs but can also update an existing installation (re-initialize it).
