### ISSUE TITLE
Skupper status shows different status at each end of two-router mesh

### ISSUE THREAD

**Issue by ChugR** [skupperproject/skupper-cli#8]
Router B connects to Router A.

Skupper status at B shows skupper enabled, and connected to ...
Skupper status at A shows skupper enabled, It is not connected to any other sites.

**Comment by grs** [comment]
Yes, at present this is 'expected' but I agree it is not desirable. At present the connections shown are based on configured connectors, i.e. the connect invocations. What we really want is actual connection stats from the router. Coming soon...

**Comment by grs** [comment]
Fixed on master in in latest 0.0.1-beta release.
